# Generated by Django 5.2.17 on 2026-10-05 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_spotlight',
            field=models.BooleanField(default=False, help_text="Feature alone in the home page 'Single Product Spotlight' section."),
        ),
    ]
