# Generated by Django 5.2.17 on 2026-10-05 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=120)),
                ('subheading', models.TextField(blank=True)),
                ('cta_label', models.CharField(blank=True, max_length=40)),
                ('cta_link', models.CharField(blank=True, max_length=200)),
                ('desktop_image', models.ImageField(blank=True, upload_to='hero/')),
                ('mobile_image', models.ImageField(blank=True, upload_to='hero/')),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='SiteSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(unique=True)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('section_type', models.CharField(choices=[('hero', 'Hero Slider'), ('featured_categories', 'Featured Categories'), ('trending_products', 'Trending Products'), ('spotlight', 'Single Product Spotlight'), ('promo', 'Promo Banners')], max_length=30)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='StoreSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Aangan Living', max_length=100)),
                ('tagline', models.CharField(blank=True, default='Handcrafted Furniture & Home Décor', max_length=200)),
                ('logo', models.ImageField(blank=True, upload_to='store/')),
                ('favicon', models.ImageField(blank=True, upload_to='store/')),
                ('primary_color', models.CharField(default='#3F3A33', max_length=7)),
                ('secondary_color', models.CharField(default='#B4684A', max_length=7)),
                ('contact_email', models.EmailField(default='care@aanganliving.pk', max_length=254)),
                ('contact_phone', models.CharField(default='+92 300 1234567', max_length=30)),
                ('facebook_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('pinterest_url', models.URLField(blank=True)),
                ('youtube_url', models.URLField(blank=True)),
                ('announcement_text', models.CharField(blank=True, max_length=200)),
                ('announcement_active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Store settings',
                'verbose_name_plural': 'Store settings',
            },
        ),
    ]
