# Generated by Django 5.2.17 on 2026-10-05 14:37

from django.db import migrations

DEFAULT_SECTIONS = [
    ("hero", "Hero Slider", "hero", 10),
    ("featured_categories", "Featured Categories", "featured_categories", 20),
    ("trending_products", "Trending Products", "trending_products", 30),
    ("spotlight", "Single Product Spotlight", "spotlight", 40),
    ("promo", "Promo Banners", "promo", 50),
]


def seed_sections(apps, schema_editor):
    SiteSection = apps.get_model("core", "SiteSection")
    for key, title, section_type, sort_order in DEFAULT_SECTIONS:
        SiteSection.objects.update_or_create(
            key=key,
            defaults={
                "title": title,
                "section_type": section_type,
                "sort_order": sort_order,
                "is_active": True,
            },
        )


def unseed_sections(apps, schema_editor):
    SiteSection = apps.get_model("core", "SiteSection")
    SiteSection.objects.filter(key__in=[s[0] for s in DEFAULT_SECTIONS]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_sections, unseed_sections),
    ]
